var test = require('tape')
var nextBoard = require('../nextBoard')
var createBoard = require('../createBoard')

test('nextBoard', function (t) {
  (function () {
    var board = createBoard(10)
    board = board.setIn([0, 0], true)
    var newBoard = nextBoard(board)
    t.false(newBoard.getIn([0, 0]), 'Example one is correct')
  })()
  ;(function () {
    var board = createBoard(10)
    board = board.setIn([1, 1], true)
    board = board.setIn([1, 2], true)
    board = board.setIn([2, 1], true)
    board = board.setIn([2, 2], true)
    var newBoard = nextBoard(board)
    t.true(newBoard.getIn([2, 2]), 'Example one is correct')
    t.true(newBoard.getIn([1, 1]), 'Example one is correct')
    t.true(newBoard.getIn([2, 1]), 'Example one is correct')
    t.true(newBoard.getIn([1, 2]), 'Example one is correct')
  })()
  ;(function () {
    var board = createBoard(10)
    board = board.setIn([0, 0], true)
    board = board.setIn([0, 1], true)
    board = board.setIn([1, 0], true)
    var newBoard = nextBoard(board)
    t.true(newBoard.getIn([1, 1]), 'Example three is correct')
  })()
  t.end()
})
